title: mi sitio web sencillo
description: p√°gena creada con JeKyll y GitHub pages
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
